### PR TITLE
OAuth2 functionality

### PR DESCRIPTION
**Pull request by rbns**
this adds some functionality required for oauth2 authentication ( #148 ), it is WIP and not working currently:

- class oauth2_client_credentials containing methods to authenticate using the [client credentials flow
](https://docs.microsoft.com/en-us/azure/active-directory/develop/v2-oauth2-client-creds-grant-flow)
- https://github.com/nlohmann/json is used to parse the json responses
- the renewal of tokens is problematic due to the const qualifier of the credentials, this requires further thought.

### CODE REVIEW

**Comment by idolum** [comment]
@rbns I added a commit to the branch so that Travis could build it with clang. Travis [migrated to Xenial](https://blog.travis-ci.com/2019-04-15-xenial-default-build-environment) and I needed to pin the build matrix to Trusty.

But it seems that the JSON library you used has an issue with detecting the right version of C++. Building it with clang produces some errors:

```
/home/travis/build/otris/ews-cpp/include/ews/json/json.hpp:14797:38: error: too
      few template arguments for class template 'less'
    using object_comparator_t = std::less<>;
```

See https://travis-ci.org/otris/ews-cpp/jobs/572449323

May the JSON library requires a higher clang version:
https://github.com/nlohmann/json/blob/develop/.travis.yml#L43
(but it is a kind of side-show and not really related to OAuth2)

**Comment by ZaMaZaN4iK** [comment]
I think it's not a good idea to simply copy nlohmann/json into the repo. Can you try to use some kind of dependency management? E.g. Conan. If you need an example, how to do it - please ping me and I will provide it.

Why I don't like manual copying:

- Harder to maintain in Unix-distros (no one like it)
- nlohmann/json is not a part of the library - that's just an external dependency. And we should work with it as with external dependency.

I don't know which policy for external dependencies is chosen in ews-cpp so my thoughts can be unapplicable here :)

**Comment by rbns** [comment]
> I think it's not a good idea to simply copy nlohmann/json into the repo. Can you try to use some kind of dependency management? E.g. Conan. If you need an example, how to do it - please ping me and I will provide it.

For the time being, I've copied it like rapidxml. I think that it would be good to have dependency management, but then everything should be managed by it, so it may be a topic for another ticket/PR. I'd like to wait for what @idolum has to say on this.

> @rbns I added a commit to the branch so that Travis could build it with clang. 
> [...]
> But it seems that the JSON library you used has an issue with detecting the right version of C++. Building it with clang produces some errors:
> [...] 
> See https://travis-ci.org/otris/ews-cpp/jobs/572449323

there is an issue (https://github.com/nlohmann/json/issues/1628) which looks similar to this one. the comments there suggest that it depends on which gcc version clang is compiled with:

> The problem seems to be due to the fact that I compiled clang from the sources on my CentOS machine, whereby GCC 4.8.5 was used, which does not support C++14 to full extent. A properly compiled clang works without problems.

**Comment by ZaMaZaN4iK** [comment]
@rbns 
> the renewal of tokens is problematic due to the const qualifier of the credentials, this requires further thought.
Can you show please where is this problematic place in the source code - cannot see. Thank you

**Comment by rbns** [comment]
> @rbns
> 
> > the renewal of tokens is problematic due to the const qualifier of the credentials, this requires further thought.
> 
> Can you show please where is this problematic place in the source code - cannot see. Thank you

I'm not that experienced with C++, so bear with me:

These are some of the relevant lines:

https://github.com/otris/ews-cpp/blob/1567f85a515a85b44950747a3acd30894a999b4d/include/ews/ews.hpp#L8104
 
https://github.com/otris/ews-cpp/blob/1567f85a515a85b44950747a3acd30894a999b4d/include/ews/ews.hpp#L8222

https://github.com/otris/ews-cpp/blob/1567f85a515a85b44950747a3acd30894a999b4d/include/ews/ews.hpp#L22621

The other certify methods just inject the right headers etc. into the requests, but with oauth2 we have to care about token renewal. In this prototype the access token and expiration time is stored in the oauth2_client_credentials object (https://github.com/otris/ews-cpp/blob/1567f85a515a85b44950747a3acd30894a999b4d/include/ews/ews.hpp#L22678) which is const most of the time, so it can't be renewed. As it should usually be a good idea to have as many things as possible qualified const, I'm not sure if this should be changed, or if there is another good solution.

**Comment by ZaMaZaN4iK** [comment]
@rbns can you mark `access_token` with `mutable`specifier?

**Comment by rbns** [comment]
> @rbns can you mark `access_token` with `mutable`specifier?

i've marked `access_token` and `expiration` mutable, and hooked authenticate into the certify method. i got no errors regarding consts while compiling locally. thanks for the suggestion!

**Comment by ZaMaZaN4iK** [comment]
You are welcome :)

**Comment by idolum** [comment]
> > I think it's not a good idea to simply copy nlohmann/json into the repo. Can you try to use some kind of dependency management? E.g. Conan. If you need an example, how to do it - please ping me and I will provide it.
> 
> For the time being, I've copied it like rapidxml. I think that it would be good to have dependency management, but then everything should be managed by it, so it may be a topic for another ticket/PR. I'd like to wait for what @idolum has to say on this.

I just support the community to find a consensus. 😉 But I prefer to have the implementation sucessfully tested, before digging into detail on how to include third-party projects. As copying a library was done before with rapidxml, doing the same with nlohman/json is at least in line with the decissions made in the past. But Conan looks interesting. Haven't heard about yet. I will take a look on it.
 
> > @rbns I added a commit to the branch so that Travis could build it with clang.
> > [...]
> > But it seems that the JSON library you used has an issue with detecting the right version of C++. Building it with clang produces some errors:
> > [...]
> > See https://travis-ci.org/otris/ews-cpp/jobs/572449323
> 
> there is an issue ([nlohmann/json#1628](https://github.com/nlohmann/json/issues/1628)) which looks similar to this one. the comments there suggest that it depends on which gcc version clang is compiled with:
> 
> > The problem seems to be due to the fact that I compiled clang from the sources on my CentOS machine, whereby GCC 4.8.5 was used, which does not support C++14 to full extent. A properly compiled clang works without problems.

If it just an issues with the compiler itself, we might ignore this. I added Xenial into the Travis' build matrix (cf. #155). @rbns, if you push again Travis will build your changes on Xenial with a newer clang as well. If this works, I think, we can drop Trusty. In particular, as Trusty isn't supportted by Canonical anymore.

**Comment by mrcheese123** [comment]
Hi all, has this branch been tested and is it working? I'm about to start making something for my workplace and I'm shopping for libraries, so I'm open to test in a live environment if needed. As this has been sitting since August, are there any issues outstanding or any reasons why this branch hasn't been merged yet?

**Comment by idolum** [comment]
@mrcheese123 Hi! The branch hasn't be tested yet with Office 365. That'sthe reason why it hasn't been merged yet. I needed a proper Office 365 account for the test. I succeded to get one, but now I need to find the time. I hope in next couple of days. But any support is highly appreciated.

**Comment by idolum** [comment]
I was able to build it and to send request to Office 365. Works partially, but still some issues have to be solved:

* `get_exchange_web_services_url()` needs to adapted to work with the `oauth2_client_credentials`
* `expires_on` should be `expires_in`
* Azure/Office 365 requires also a `scope` for requesting the credentials
* Access token is not provided properly in the requests to Office 365

But these issues will be addressed in a follwing pull request.

**Pull request merged**
