### PR TITLE
Add use of curl error buffer

### PR DESCRIPTION
**Pull request by SebastianBecker2**
curl_ptr now registers a buffer for curl for detailed error
information. This will be forwarded into the curl_error in case of an
error when calling curl_easy_perform. curl_error, in turn, is moved out
of the internal namespace to allow the user to catch this specific
exception.

I'm quite unsure on how to implement it properly.
For example the move constructor and move assignment operator
of curl_ptr, re-register the error buffer after moving the curl pointer.
But I'm not sure how else to implement it, while still allowing move
operations.
And furthermore the curl_error class is now publicly available.
I'm not 100% on why it was internal in the first place. But I hope
making it public doesn't break anything.

If you have any ideas, tips or opinions on this, please feel free to
comment. Any help is welcome.

### CODE REVIEW

**Comment by bkircher** [comment]
Sorry I missed this. Do you still want to get this in? I can review this but I lack testing infrastructure so to speak (no access to an Exchange server anymore).

**Comment by SebastianBecker2** [comment]
Don't worry. I was pretty busy myself too.
I had it working with this change for a while now. It was quite helpful.
So yeah, I think merging it is a good idea.

**Comment by bkircher** [comment]
Ok, then… lets do it.

I just have no way of testing changes here in a reasonable way anymore because most of the changes really require an Exchange Server to test against.

**Comment by idolum** [comment]
I can't say anything about the details, but at least I was able to build the library with the changes and passed all tests. So, it looks fine from my point of view.

**Comment by bkircher** [comment]
False sense of security when one uses C++ 😄

**Pull request merged**
